### ISSUE TITLE
select doesn't respect the width of the parent

### ISSUE THREAD

**Issue by aguaviva** [Chalarangelo/mini.css#108]
The following select doesn't respect the width of the parent

![image](https://user-images.githubusercontent.com/5200915/31865320-8a46adc8-b76d-11e7-990c-cb9dd761e9cf.png)

see below:

![image](https://user-images.githubusercontent.com/5200915/31865308-3b81cdd0-b76d-11e7-83d0-2dcfded3f7ab.png)

**Comment by Chalarangelo** [comment]
Wow, this is a pretty nasty one. Could you provide me with a code sample to figure this out? It's probably something simple like `overflow: hidden`, but I need to test this in a Codepen to make sure. Sorry for the inconvenience!

**Comment by Chalarangelo** [comment]
## Update

This bug is caused by the `select` element lacking the `max-width: 100%` property, which would make it fit inside its parent container properly. Apart from that, to make sure `option` elements display properly, I will be adding the following styling to them:
```
option {
  overflow: hidden;
  text-overflow: ellipsis;
}
```
Note that this will hide any excess text from the `select` element.
On a side note, I have noticed that using the `size` attribute sort of breaks the custom fix for the `select` element, so I will update the selectors accordingly.

Finally, as a piece of advice: This kind of content is **not** a good fit for a `select` element in general and using a group of `radio` buttons would be a better option for this kind of selection.
