### ISSUE TITLE
Question - Integration with Angular

### ISSUE THREAD

**Issue by Martin-Andersen** [Chalarangelo/mini.css#121]
Hi any recommendations on how to integrate mini.css with Angular?

**Comment by Chalarangelo** [comment]
I'm not sure if there are any issues integrating mini.css with Angular, haven't tried it before. I suppose that there should be no issues due to the fact that mini.css is pure CSS, so it won't conflict with any JS code, plus pretty much all of the class names in mini.css are customizable, so you should be able to configure it to your liking.

**Comment by Chalarangelo** [comment]
No feedback or new comments, I am closing this then.
