### ISSUE TITLE
Tables: Cannot color an entire row in v3

### ISSUE THREAD

**Issue by SkewedZeppelin** [Chalarangelo/mini.css#127]
* Framework Version: v3
* Flavor used: default
* Browser: Firefox 60 and Chromium 66
* Code to reproduce: https://gist.github.com/SkewedZeppelin/11928804db4172b9eb84a8243b2d70cc
* Bug description: Coloring an entire row of a table by applying an inline color style to a \<tr\> element does not work, but previously worked in v2.3.7.

* Screenshots:
v2.3.7
![v2 3 7](https://user-images.githubusercontent.com/8296104/40091615-ca06fea8-5886-11e8-83b7-6edf06ba1e1b.png)
v3
![v3](https://user-images.githubusercontent.com/8296104/40091618-cea52336-5886-11e8-9dbc-c726aa855287.png)

**Comment by Chalarangelo** [comment]
Due to the way **Gluon** is coded, inline styles will not work exactly like that. But you have two other options:

1. Use a class on the `tr` that applies a style to children (not preferred):
```css
tr.my-class > td {
  color: red;
}
```

2. Alter the CSS variable in the parent element, children will inherit it (best practice):
```html
<tr style="--table-body-fore-color: red">
  <td>Data here</td>
  <td>More data</td>
</tr>
```

Sorry for the long wait, but I hope this will help you resolve your issue.

**Comment by SkewedZeppelin** [comment]
The second method worked perfectly. Congratulations on the release :tada:!
