### ISSUE TITLE
Small and large buttons look wrong when in a button group

### ISSUE THREAD

**Issue by aeons** [Chalarangelo/mini.css#129]
* Framework Version:
3.0.0-alpha.3
* Flavor used:
Default
* Operating System/Browser:
Mac, Firefox, Safari and Chrome
* Code to reproduce:
```
<div class="button-group">
  <button>Horses</button>
  <button>are</button>
  <button>neat</button>
</div>

<div class="button-group">
  <button class="small">Horses</button>
  <button class="small">are</button>
  <button class="small">neat</button>
</div>
```
* Screenshots:
<img width="792" alt="screen shot 2018-05-17 at 20 25 30" src="https://user-images.githubusercontent.com/1432894/40196369-90886384-5a10-11e8-9987-14f1e5c842fb.png">

* Bug description:
Buttons in a button group do not behave properly when they have either the class `small` or `large`.
* Additional information (Optional):

[Note]: # (Please describe what the bug is, what component/module causes it and how it differs from expected/intended behavior)
[Note]: # (Include screenshots of the reported bug whenever possible to best clarify)
[Note]: # (Always try to include code to reproduce the problem, as well as system specifications to make tracking easier)
[Note]: # (Codepen links, additional information, suggestions, articles etc. are greatly appreciated)
[Note]: # (If you want to suggest a feature or your issue doesn't classify as a bug report, please do not use this template)

**Comment by Chalarangelo** [comment]
This is quite an interesting issue, I'll see if I can figure it out before the next release.

**Comment by Chalarangelo** [comment]
`.button-group` elements were never designed to work with `.small` and `.large` buttons. If you really want to make them compatible with that, you would have to tweak the `_input_control.scss` file to produce a selector with higher specificity or somehow get the mixins output before the `.button-group` rules in your final CSS (essentially, if you swap them in your CSS file, so that `.small` and `.large` come before `.button-group`, it will all work as they have the same specificity).

I will not be implementing this in the framework itself, as it will add quite a lot of overhead with the selectors, but swapping the order of selectors in the CSS should work just fine.

**Comment by aeons** [comment]
Cool, maybe a short note in the docs would make it clear that you should probably only use button-group with regular buttons?

**Comment by Chalarangelo** [comment]
Yup, I will add it soon!
