### ISSUE TITLE
Missing table footer (<tfoot>) definitions

### ISSUE THREAD

**Issue by lemmingz** [Chalarangelo/mini.css#135]
* Framework Version: 3.0.0
* Flavor used: Nord
* Code to reproduce: https://codepen.io/anon/pen/OEraXG
* Bug description: The definitions for the table footer is missing. Due to the flex display the footers content appears unstyled beneath the table header (because tfoot has to be defined before tbody).

**Comment by Chalarangelo** [comment]
The notes for the [Table](https://minicss.org/docs#tables) element clearly state `<tfoot>` is not supported due to the way tables are styled with Flexbox. This is an issue that is not going to be addressed as it is (as far as I can tell) impossible to make this work anyways, due to the fact that `<tfoot>` elements come before the `<tbody>` element.

**Comment by lemmingz** [comment]
Thanks for your hint.

Well, I think it is not impossible to handle the tfoot. 
Initially I did a little test with flex order:  https://codepen.io/anon/pen/qKgZbO and it doesn't look that bad.

**Comment by Chalarangelo** [comment]
This seems interesting, I'll give it a shot and report back with my results.

**Comment by Chalarangelo** [comment]
The main issue with `tfoot` is that it breaks the `.horizontal` table variant. I will add a note for this fix for the normal tables, as it's a one-liner for people who need it.
