### ISSUE TITLE
Collapsible navigation menu

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#43]
[CSS-only collapsible hamburger menus exists](http://codepen.io/erikterwan/pen/EVzeRP), so this would be a nice addition to mini.css.

**Comment by Chalarangelo** [comment]
**mini.css** has been against hamburger menus up until now as they seem to be considered a bad design paradigm by many. I'll revisit the subject and see what's better (maybe via a poll on Hashnode).

**Comment by naasking** [comment]
I agree they're overused, but legit uses do exist. The defaults should lead you towards the correct behaviour, but it would be nice to have an opt-in collapsible menu for when it actually makes sense. But, up to you!

**Comment by Chalarangelo** [comment]
Like modal dialogs (issue #46), hamburger menus are not a priority and, when implemented, they should be their own component, with their own repository for easier support. The implementation I had in the previous version of **mini.css** was lacking, so I decided to cut them in favor of a flatter navigation system. I am probably not going to build the hamburger menu component myself, but if anyone builds it, I will provide a link to it through the toolkit's pages, so that people can use it.

**Comment by naasking** [comment]
I took your suggestion and did a little reading, and plain hamburgers indeed are problematic for older users who don't see it as a menu or clickable. However, adding borders to make it button-like improved engagement, as did using the word "menu" or using an ellipsis, which everyone learns early-on means "there's more".

I'm just spit-balling here, so *if* you were to support a collapsible menu, a button-like ellipsis or "menu" would work best.

Collapsible overflow behaviour would have other uses though. For instance, breadcrumbs that overflow the context look weird. The most recent entries are the most likely to be used, so if the earlier entries could collapse into an ellipsis menu that would be pretty neat. I understand this isn't high on the priority list though.

**Comment by Chalarangelo** [comment]
It's not very high priority, but it's a valid improvement to the toolkit. I also think, due to the fact that I have no experience with the hamburger component yet, some images might be useful in designing such a component to be accessible and easy-to-use. The hamburger menu will be an extension module in a different repo and, if nobody else starts developing it, I will begin working on it post-v2.1 (late January, early February).

**Comment by Chalarangelo** [comment]
The issue will be closed. The specifics of the module have been added to the list (#59) and is now awaiting implementation.
