### ISSUE TITLE
Modal (popup) dialog style need

### ISSUE THREAD

**Issue by ozgurrgul** [Chalarangelo/mini.css#46]
> Alerts replace modal dialogs, along with messages, notifications and traditional alerts with a simpler, easier design paradigm.

Alerts are good and I'm using it, but a modal dialog is one of the elements that should be in a CSS framework. Because alerts are not enough in terms of UI experience. Think about a facebook post like list. 

That would be good to see modal. Right now I'm using [w3-css modal](http://www.w3schools.com/w3css/w3css_modal.asp).

**Comment by Chalarangelo** [comment]
Modals are never going to be part of the base toolkit. However, I will eventually create a modal component that will have some Javascript as well in its own repo. I will update this issue when that happens!

**Comment by naasking** [comment]
[Picnic css](http://picnicss.com/documentation#modal) has a CSS-only modal dialog, so it's certainly possible.

**Comment by Chalarangelo** [comment]
@naasking A modal dialog can be implemented with pure CSS, however as I found out in a previous release accessibility might be an issue. I will research this further and report my findings before implementation.

As far as the modal dialog is concerned, there are two key reasons it is not going to be part of the base **miini.css** experience, but rather a complementary project of its own:

1. I strongly disagree with the use of modals on certain devices, such as phones and tablets, especially when not well-used. No matter how well a modal dialog might be implemented, there is still potential for abuse. **This is a strongly opinionated decision**, but I stand by it, as I believe the modal dialog pattern can be easily replaced by less intrusive components, such as the alerts provided. However, alerts need some more attention, which they will be given in the next few patches and minor releases, so that some functionality is added to them.
2. Due to **mini.css** being a minimal framework, I try to cut out some of the extra fat, such as modals, but I would love for these components to be compatible with the rest of the framework (probably card-based), so that people who need them can use them. In order to keep the toolkit tiny, these components should be their own repositories, so that more people can contribute to them and give them the love they deserve. After all, I am just one person, so I cannot keep developing and supporting components ad infinitum, especially ones I dislike as patterns.

(Issue will be kept open until a modal dialog component is released.)

**Comment by Chalarangelo** [comment]
The issue will be closed. The specifics of the module have been added to the list (#59) and is now awaiting implementation.
