### ISSUE TITLE
Checkbox and Radio inputs inside labels

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#51]
Some web frameworks generate ids automatically, so it's sometimes difficult to designate checkboxes and radio inputs using the label's "for" attribute. Nesting the input inside the label as allowed in HTML5 would solve this problem, and the checkbox hack should work if you add selector for `label>[type="input"]` or an explicit class the way [Picnic CSS](http://picnicss.com/documentation#checkbox) does it.

If the input-group class would also apply to the label, then that would be ideal since it eliminates redundant markup:

    <label class="input-group">
      <input type="checkbox" id="check1" tabindex="0"> 
      <span for="check1">Checkbox</span>
    </label>

**Comment by Chalarangelo** [comment]
This is an interesting suggestion. I'll check for conflicts and, if none exist, will try to implement it in **v2.1**. The class might not even be required, making it even simpler to use and remember.

**Comment by Chalarangelo** [comment]
I just now got to dealing with this issue, sorry for the delay.

I was thinking of moving the `input`s inside the `label`s, but this might have undesirable implications in terms of accessibility and/or mnemonics for people who use **mini.css**. I will look into this further in the following days and give you an update.

If you have the time, could you please provide me with an example of a web framework that could be a culprit causing this problem? Just for research!

**Comment by Chalarangelo** [comment]
After some quick research, it seems like most people prefer explicit labeling of form controls, rather than implicit. Many of the sources I found state that implicit labeling can be a problem for screen readers. In fact, [MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element) states the following:

>  A widget can be nested inside its `<label>` element but even in that case, it is considered best practice to set the `for` attribute because some assistive technologies do not understand implicit relationships between labels and widgets.

Most ARIA guidelines I have found suggest using explicit over implicit labeling, at least for the time being. In fact, the latest draft of WCAG 2.0 doesn't even mention implicit labeling in its techniques ([WCAG 2.0, H44](https://www.w3.org/TR/WCAG20-TECHS/H44.html)).

Based on the fact that accessibility comes before compliance with web frameworks and seeing as most of the other CSS toolkits and frameworks use explicit labeling for most of their elements, I am closing the issue for now. If, at some point, implicit labeling becomes the norm, I would be glad to reopen the issue and change the way **mini.css** implements the checkbox and radio button components' labels.
