### ISSUE TITLE
Tweak default colour choices

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#52]
I'm slightly red-green colour blind, and the difference between mini.css's reds and greens is difficult to see without squinting. Not a high priority since this is customizable, but I suggest lightening or darkening the shade of one or both of the colours to make it more accessible. I think making the green lighter and the red darker would distinguish them better, but plenty of variants exist. Bootstrap's colour choices are quite good if that helps.

**Comment by Chalarangelo** [comment]
I am slightly red-green colorblind as well, however I had no difficulty seeing the difference. I will try to change the colors a bit, so that it makes it easier for people to see. I am using the Google Material color palette, so finding the proper shades should not be a huge problem.

As this is kind of urgent, I will release **v2.0.2** in the next few days to resolve the issues. Thank you for the feedback!

**Comment by Chalarangelo** [comment]
@naasking I hope that the new colors make it a bit easier for colorblind people to see the differences between `.tertiary` and `.secondary`. The new patch will be up in the next days, sorry for the delay!
