### ISSUE TITLE
Multi-row table headers and table grid compatibility

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#54]
Consider the following table:

    <table>
        <thead>
            <tr><th colspan="2">Weights</th></tr>
            <tr><th>kg</th><th>lbs</th></tr>
        </thead>
        <tbody><tr><td>1.0</td><td>2.20462</td></tr></tbody>
    </table>

Since the cells are all bordered, I expected the spanning heading to also be bordered on every side, but obviously they're not here. Not sure if intentional.

I also can't control the width of the table using the grid classes.

**Comment by Chalarangelo** [comment]
I haven't tested this at all. I will give it a shot and see what happens and figure out the best way to deal with the issue. Thanks for reporting it!

**Comment by Chalarangelo** [comment]
### Update

As far as multiple rows in the `<thead>` are concerned: While this is valid HTML and causes no real problems, it seems like it needs a lot of workarounds to be fully accessible (as seen [here](https://www.w3.org/WAI/tutorials/tables/irregular/)). 

As far as controlling the table's width using `grid` classes, I consider this a bad idea, as tables do not behave properly when styled with *flexbox*. It's always a better idea to let tables style themselves properly. Smaller screens will change to card view to deal with the situation and, if you want to have a better time viewing tables, you can always use `.horizontal` tables. 

Provided that none of these issues can be "fixed" in a very specific way, I will add notes and workarounds in the `table` module's documentation, so that people are aware of the limitations and problems that might exist.

**Comment by naasking** [comment]
Just some thoughts:

 1. Nice find on the accessibility issues, so simply documenting aria-hidden requirements for such column-spanning headers would be totally fine IMO. The visual styling should just work though, and seems doable.
 2. Re: letting tables style themselves, this isn't always feasible. It's not uncommon to have cells whose text you don't want to wrap, where other cell text can wrap as needed. I always think of widths in terms of grid columns, but that isn't necessarily applicable to any single framework. Note that you don't need to use flexbox to style the tables, you can overload the meaning of the grid classes for th/td so they work with tables.

**Comment by Chalarangelo** [comment]
1. As far as the visual styling is concerned, I will post a fix in a note or a *Do* section in tables, to help people get started. Lots of testing and maybe some sort of redesign might be required to make this work by default, as there are many issues that need solving in respect to tables.

2. Overloading the grid classes would bloat the framework quite a lot and the tradeoff is not worth all that in terms of functionality. I will look further into the matter and hopefully find a solution that is at least satisfactory enough, but I cannot promise that this will be resolved before **v2.1.0**. I might add this functionality in a later patch.
