### ISSUE TITLE
Grouped buttons don't look right on Android

### ISSUE THREAD

**Issue by thdoan** [Chalarangelo/mini.css#63]
This is what I see on the latest version of Chrome for Android 4.4:

![screenshot_2017-04-05-20-05-41](https://cloud.githubusercontent.com/assets/4110567/24704895/20fe9534-1a3c-11e7-824b-6516a4a33305.png)

**Comment by Chalarangelo** [comment]
Hello @thdoan, thanks for reporting this issue! I do not currently own any device that can reproduce this problem, which makes debugging it a little bit more difficult than usual. I will, however, try to find a way to reproduce it and/or ask for help online (possibly SO) if I cannot figure out myself where the issue is coming from.

In the meantime, I would like you to test out this [pen on Codepen](http://codepen.io/chalarangelo/full/xRMPJG/) and, if you have the same issue (which is most likely), report back with another screenshot so that I can see exactly how it behaves. If possible, I would require some more information, such as your version of Android (as seen under your device's settings/info), any relevant information on the browser you are using etc. (I am not entirely certain what info I need to track down a bug in the browser's implementation of the code, if that is the case, but anything would help me find information online). If your browser has an option to view the site as the desktop version, do try it out and if the error perceeds, please provide me with a screenshot. Finally, check the rest of the documentation and samples and tell me if anything else doesn't work as expected, as there is a possibility that this might be a Flexbox-related issue and could be widespread over many modules and components.

**PS:** Sorry for asking for so much info, but debugging this is quite difficult without a device running the same OS and browser and setting one up might take a little while, so I would rather have a more detailed report of the problem before I delve into it using an emulated device or similar to better understand its nature and check online if this could be a common problem. Thanks again for reporting!

**PS2:** I suspect that the culprit here is the button's `height` property, which might be causing the flexible buttons to collapse on top of each other. If my assumption is correct, I might be able to work out a solution without a device to test it on. Said solution could be testable within the day or tomorrow, so stay tuned!

**Comment by Chalarangelo** [comment]
## Update 

I was able to reproduce the problem on certain versions of Chrome for Android and the ASUS Browser on Android, as well as Chrome 57 on Windows 7. Seems like the problem is reasonably common, so I might be able to fix it more easily than I thought.

The issue is now high priority and I will aim to resolve it before the release of **v2.1.1**.

**Comment by Chalarangelo** [comment]
## Update 2

The problem has been found to be due to the way that Chrome renders `flexbox`-based objects when the orientation is vertical. Somehow, using `flex: 1 1 auto` which is different from `flex: 1` apparently (see [here](https://css-tricks.com/boxes-fill-height-dont-squish/)) on the child elements of the button group, seems to resolve the problem. Thus you can just add the following CSS snippet to solve the problem for now.

```CSS
.button-group .button, 
.button-group [type=button], 
.button-group [type=reset], 
.button-group [type=submit],
.button-group a.button, 
.button-group button, 
.button-group label.button {
  flex: 1 1 auto;
}
```

As usual this is a temporary solution and the above code will be tested in depth and incorporated in the **v2.1.1** release to deal with this problem across the board. As soon as the update is deployed, you are advised to use the latest release instead of this quick fix to solve the problem. 

A **demo** showcasing the fixed display of the grouped buttons can be seen in [this pen](http://codepen.io/chalarangelo/full/dvLKaV/).

**Comment by thdoan** [comment]
Thanks a lot for the quick patch. You resolved it even before I got a chance to reply with the requested info, so now I guess I don't have to do it :-). For what it's worth, I'm using Chrome v57.0.2987.132 on Android 4.4.2 with 1080 x 1920 resolution on 5.2-inch screen (Sharp Aquos Xx 304SH). I went through all the examples in vertical orientation and that was the only issue I noticed. Keep up the good work!
