### ISSUE TITLE
Suggestion: replace rawgit with gitcdn in sample code

### ISSUE THREAD

**Issue by thdoan** [Chalarangelo/mini.css#64]
Have you tried http://gitcdn.link/? I think it's an improvement on rawgit for several reasons:

- If you point it to your master branch (or whatever branch has the latest code), then the CDN link will always redirect to the latest version of the file since it redirects to a URL that has a built-in cache buster (the URL hash changes every time you update the source file). I used to include rawgit in the sample code of my own projects, but I found people who were using the rawgit URLs were not getting the latest version. I either had to regenerate the rawgit URL, or like you organize the code into a directory named after the version number (in both cases I still had to update the sample code every time I push an update). Using gitcdn.link I can just stick with one URL in all my sample code and never worry about having to update it for every new release.
- If you use `min.gitcdn.link` instead of `gitcdn.link`, it will automatically minify the JS or CSS file! Yay, no more having to keep a separate minified version in your code base.

Here's the full list of benefits as outlined by project maintainer Shane Gadsby:

- Lets you link to specific commits as well as auto-get the latest (a.k.a. master)
- Incurs no damage from high traffic volumes; RawGit asks that its dev.rawgit.com links be only used during development, whereas GitCDN gives you access to the latest version without the danger of the servers exploding
- Gives you the option of auto-minifying your HTML, CSS and JavaScript (https://min.gitcdn.link), or serving it as written
- Adds compression (gzip)
- Adds all the correct headers (Content-Type, Cache-Control, ETag, etc.)

[[Source](http://stackoverflow.com/a/31066555/452587)]

**Comment by Chalarangelo** [comment]
Wow! This does seem a lot more promising and I think it is a lot easier for people to use, instead of having to update to the latest release every single time, plus it will resolve a lot of issues stemming from the fact that people might be using legacy versions. I will try it out and probably use it instead of the current rawgit solution. 

By the way, there is also another alternative, [cdnjs](https://cdnjs.com/libraries/mini.css), where **mini.css** is available, however their CDN doesn't seem to have noticed the latest release (it's supposed to auto-update on release), so if I figure out how to deal with this whole update business, I will include a link to it as well in the docs. It is still version-based, but I know many people use and like it.

Thank you very much for the suggestion, I will be looking into it very shortly!

**Comment by thdoan** [comment]
No problemo. I've been trying it out for almost a week with no issues so far, but they're a small outfit providing a free service, so you never know.

Yeah I'm aware of cdnjs and link to that whenever I can, but unfortunately I can't get my projects hosted on there because none of them have the minimum required 100 stars on GitHub, yet :(.
