### ISSUE TITLE
How do you center stuff?

### ISSUE THREAD

**Issue by ghost** [Chalarangelo/mini.css#68]
Today I tried to center a button horizontally. I couldn't find a class that does it. Is there one? If so can you please add it to the documentation? I searched every page of the documentation and found no reference to "center".

**Comment by Chalarangelo** [comment]
## Explanation and reasoning

In short, no, there is no centering class that is shipped with **mini.css** right now. The long version is as follows:

The center-block class is part of the `utility` module and is considered legacy (meaning not shipped as `on-by-default` in any flavors), for two reasons primarily:

1. The way it is built is a bit old-school and there might be better ways to deal with this problem. The implementation provided in the `utility` module is based around the old `float`-based systems, so it might not work that well with the current `flexbox`-based systems. You can enable it, if you would like (see below), manually.
2. Atomic CSS (as in object-oriented) is **not** supported by the framework (we consider it an anti-pattern) and will probably not be added unless many people ask for it, due to the fact that many things can and will be useless and clutter it up quite a lot. Thus, we do not provide simple classes like centering and alignment, which can be coded easily enough by anyone in no time and might not be used a lot (or at all in certain cases).

## What you can do

There are a few ways to tackle the probem you are facing:

Just duplicate the flavor file (`mini-default.scss`) and add two lines right before the first `@import` statement:

```scss
$include-center-block: true;
$center-block-name: 'center-block';
```

Compile your flavor file (I suppose that you are familiar with compiling Sass). This will create a `.center-block` class, as follows:

```css
.center-block {
  display: block !important;
  margin-left: auto !important;
  margin-right: auto !important;
}
```

Alternatively, you can copy-paste the above CSS code and not bother with the flavor file. For most cases involving text only, however, you can use a simple class like this:

```css
.center {
  text-align: center;
}
```

In the case you are describing, the above code will not work properly, meaning you should use the first solution I suggested (flavor file editing or copying the `.center-block` class provided).

## Notes

There is no intent of adding atomic classes and patterns to the framework, as they are pretty bad in terms of bloat and do not provide any significant usability for most cases (none that cannot be easily written by the user). If, however, there is a lot of users asking for said feature, it will be considered and maybe built as an extra module, one not enabled by default. As it currently stands, the official solution to the problem is to write any extra CSS needed for simple things like this.
