### ISSUE TITLE
Margin on input fields making it goes out of the parent box

### ISSUE THREAD

**Issue by admxxi** [Chalarangelo/mini.css#75]
Hi! Just wondering if there is anyway to fix that, I had to remove the side margin from input fields.

Regards,

![issue-mini-css](https://cloud.githubusercontent.com/assets/10850289/25801366/32380868-33e5-11e7-8fce-1ca6de503377.png)

**Comment by admxxi** [comment]
I am using input fields with width: 100%.

**Comment by Chalarangelo** [comment]
Hi, thanks for reporting this! I'll see what I can do, there might be a possible workaround until I actually patch this in the next release. Could you provide me with a snippet to test this with?

**Comment by Chalarangelo** [comment]
Hi, thanks for reporting this! I'll see what I can do. From a couple of quick tests, however, I would suggest you replace `width: 100%` with something like `width: calc(100% - 0.625rem)`. Tell me if that helps.

**Comment by admxxi** [comment]
Check it out! http://jsfiddle.net/admxxi/1wxxuj0p/4/embedded/

**Comment by admxxi** [comment]
Exaclty What I did, anyway, I would like to contribute with the project if it is possible.
Thanks for your reply

**Comment by Chalarangelo** [comment]
Thank you for your time! I am always looking for new contributors, so if you have any suggestions, ideas or if you find any bugs, let me know. 

As far as development of the project is concerned, the main codebase is being restructure a little bit right now, so it might not be the best time to jump right in, but after the release of **v2.2.0**, I'd be happy to get more people onboard. 

What you can do is develop your own flavor and/or help with documentation, templates, tutorials etc. I will get around to writing a decent contribution guideline document in the next weeks, so that more people can partake in the development of the framework.
