### ISSUE TITLE
Select styling bug on mac os

### ISSUE THREAD

**Issue by zoxon** [Chalarangelo/mini.css#80]
![image](https://cloud.githubusercontent.com/assets/3866196/26778113/b80bdfb4-4a01-11e7-8507-c95a9af2a6ba.png)

Chrome 58.0.3029.110 (64-bit)
Mac OS Sierra 10.12.5

This bug is reproduced on Safari 10.1.1 (12603.2.4) too

**Comment by Chalarangelo** [comment]
Thank you very much for reporting this!

What exactly is the bug? It looks unstyled as far as I can tell. Is that the problem?

**Comment by zoxon** [comment]
Thank you for quick response. Dropdown is looks unstyled.

**Comment by Chalarangelo** [comment]
Well, this is part of the *progressive enhancement* idea of the framework. Certain components will use a fallback instead of the custom styling under circumstances (OS, browser, feature support). Although I'd love to be able to fix this issue, problem is I don't have a system running said OS, so my only options are to rely on the help of people using said OS and browser to indetify the cause of the problem for me.

As far as I can tell this is not a browser bug, as Chrome displays the dropdown properly on both Windows and Linux (tested both), so it's an OS bug. If you have some experience with CSS, why don't you try inspecting the element and fiddling with its style (padding, borders etc) to see if anything works? As soon as you figure out what might, post it here or even better make a Codepen, so I can see what I can do to fix this permanently. 

I'm really sorry that MaxOS support is not as great as everything else, this is due to me not having an Apple platform to test on. I'll try to figure out if there is any way to test these things myself. Sorry for all the inconvenience!

**Comment by zoxon** [comment]
This code can help. But you need to create  a custom dropdown arrow.
```css
select {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```
I have added this styles in chrome and now it looks like this

![image](https://cloud.githubusercontent.com/assets/3866196/26810415/66b584bc-4a8d-11e7-83c6-8c508063a72a.png)

**Comment by Chalarangelo** [comment]
There might be a possible workaround, using something like what you just did and some `:after` styling to make it look like a dropdown. I'll see if this can be fixed at the root of the problem, otherwise I will post a workaround for people with this kind of problem. 

Additonally, one could go asking around Reddit (/r/webdev, /r/css) and/or StackOverflow for possilble reasons of this happening and how to fix said issue.

**Comment by Chalarangelo** [comment]
#82 addressed this issue in a pretty smart manner. I took that code and improved it, essentially unifying the way `<select>` elements will look across all platforms and browsers. Update will be live in a little bit!

**Comment by s-comp** [comment]
Hello where I can see this solution?
