### ISSUE TITLE
The styling of the page is broken

### ISSUE THREAD

**Issue by Narven** [Chalarangelo/mini.css#85]
For me the [http://minicss.org/progress#basic-progress-bar](http://minicss.org/progress#basic-progress-bar) page the layout is broken

[https://www.dropbox.com/s/6osbta9ozlcp7vg/Screenshot%202017-06-22%2012.40.32.png?dl=0](https://www.dropbox.com/s/6osbta9ozlcp7vg/Screenshot%202017-06-22%2012.40.32.png?dl=0)

is kind bad for a css framework

**Comment by Narven** [comment]
Google chrome, Version 59.0.3071.104 (Official Build) (64-bit)
MacOS

**Comment by Narven** [comment]
Is something on the **Basic progress bar** area. The progress bars are side by side, instead of top of each other

**Comment by Chalarangelo** [comment]
~~Uhmm, what exactly do you mean? I can see from your screenshot that the progress bars appear on the left side of the section and there's three of them, as expected (one below the other). Validating the HTML and CSS shows no errors. Any more information on what exactly is wrong?~~

I think I can see it on Chrome... hmmm, I'll see what's wrong.

Turns out it's a typo in the card's class. Fixing immediately. Thanks for reporting!

**Comment by Narven** [comment]
thanks for the framework
