### ISSUE TITLE
Mini.css too opinionated about html structure.

### ISSUE THREAD

**Issue by danielstaleiny** [Chalarangelo/mini.css#86]
Hi, I would like to find out if there is possibility to donwload just some of the components of mini.css ? I would like to get just utilities and core of mini.css,

Another issue I am having is that mini.css is too opinionated  about structure of html. I understand that you want to write just html of the core functionality and it will work but it makes really pain to work with if you for example decide to use **nav** as navigation but  styled as **header** and **header** as regular component without extra styling. 

Is there option to maybe move base styles to css classes instead ? or is this intentional feature ? thanks for answers. 

I guess my only option is to download mini.css and modify it to my liking. which is not a problem. :)

**Comment by Chalarangelo** [comment]
Hello! The whole point of the framework is to provide styling for html elements in order to make markup for pages semantic. Using a `<nav>` as a *header* is a really bad idea as far as my experience suggests and I would advise you not to do this. 

If you want to include only certain modules, you can create you own flavor file, similar to the ones already in 📁 [flavors](https://github.com/Chalarangelo/mini.css/tree/master/src/flavors). 

Certain styles can be customized from the existing modules, however if you want to make everything class-based instead of element-based, you will have to manually alter parts of the source code, replacing elements with appropriate classes. 

If you need any help making modifications, feel free to leave a comment below and I will help you out!

**Comment by Chalarangelo** [comment]
There hasn't been any activity on this issue for a few days, I'm closing it for now and I will reopen if it's active again!

**Comment by danielstaleiny** [comment]
No worries. I will modify my custom flavor for what I need. Thanks for all info above.
