### ISSUE TITLE
Support input type=date

### ISSUE THREAD

**Issue by tomap** [Chalarangelo/mini.css#90]
Hi,

Currently input type=date are not displayed nicely at all :(

I added the following to have a better display:

```
[type="date"] {
    box-sizing: border-box;
    background: #fafafa;
    color: #212121;
    border: 0.0625rem solid #c9c9c9;
    border-radius: 0.125rem;
    margin: 0.25rem;
    padding: 0.5rem 0.75rem;
    flex-basis:inherit!important;
}

```

the last line should be improved to something like 
.input-group.vertical > input[type=date]{
    flex-basis:inherit;
}

Also, I'm not sure why you are adding -webkit-flex-basis
It seems the default flex-basis is supported in your compatibility matrix

Thank you

Thomas

**Comment by Chalarangelo** [comment]
Hello,

Your fix seems to work on supported browsers, however, due to [lack of support](http://caniuse.com/#feat=input-datetime) in two major browsers (Safari and Firefox) right now, this feature is currently on hold. As far as I am concerned, you should remove the `!important` line and add something like this in its place:

```
.input-group > input[type=date]{
  -webkit-flex-basis: inherit;
          flex-basis: inherit;
}
```

When date inputs are universally supported, I will be adding the necessary styles to the framework. At this moment, they would only bloat it with a reason in many cases (plus I rarely see people use it on anything other than booking websites). 

The `-webkit-` prefix is added to the flexbox properties as a last resort for older browsers, such as many versions of the Android Browser and the UC Browser for Android. This does not mean that these browsers are fully supported but until their market share is really tiny, I am going to keep this workaround, so layouts and core features work at least to an extent instead of not at all. You can see their market share [here](http://caniuse.com/#feat=flexbox).

**My suggestion:** Seeing that your solution works, you can just copy the `mini-default` flavor file and add this code after the `input_control` module's code and then recompile the flavor file with the additional rule, effectively incorporating your additional styles to the framework.

**Further action:** I will close the issue and add the `on hold` label for now, but I will definitely reopen it when the time comes to add this feature. It's something I've been trying to add for a while, however browser support never made it to the point that it should, not yet anyways.

**Comment by tomap** [comment]
Hi, when you start looking again at this, please include `<input type="time">` and `<input type="month">` also.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month
Thank you

**Comment by Chalarangelo** [comment]
I'm not entirely certain these elements will be supported ever, unless browsers agree among themseleves which one is the definitive element to use for time and dates. I'll look into it before **Gluon** releases, but don't get your hopes high.
