### ISSUE TITLE
Switch inside input group non fluid display with overflow on the left

### ISSUE THREAD

**Issue by tomap** [Chalarangelo/mini.css#96]
Hi,

I noticed that when uting input group without fluid, switches are not properly displayed:
https://codepen.io/anon/pen/PKLBKP
Am I missing something ?

**Comment by Chalarangelo** [comment]
Hi, thanks for reporting this. I'll see if this is a bug in the framework or something that wasn't documented properly. Theoretically, the should work with non-`.fluid` `.input-group`s, but there might be a bug I haven't noticed before. Sorry for the inconvenience.

**Comment by Chalarangelo** [comment]
As of now, it seems like non-`.fluid` `.input-group`s are not responding so well to the `.switch` component, due to the left-side spacing. A temporary solution is to add a `margin-left: 2rem` in the `.input-group`'s `style` to make sure the component is properly spaced on the left.

### Example

```html
<form>
  <fieldset>
    <legend>Simple form</legend>
    <div class="input-group" style="margin-left: 2rem">    
      <input type="checkbox" id="check" tabindex="0">
      <label for="check" class="switch">Yes or no?</label> 
    </div>
  </fieldset>
</form>
```

However, this is a **temporary solution** and this bug will be looked into for the next release. Due to the fact that the framework is soon to be migrated to a new **v3** codebase, this issue might persist until the next major release, at which point the new architecture of the framework will render this bug obsolete (basically all `.input-group`s are going to be fluid, either vertical or horizontal, so this issue will be non-existent at the time). 

For the time being, I am going to close the issue, however I will take the time to try and resolve it in a future minor version patch, if at all possible. 

Thanks again for reporting this issue and asking for help with the framework!
