### ISSUE TITLE
Hamburger's HOME button has broken behaviour in PWA flavor

### ISSUE THREAD

**Issue by quantuumsnot** [Chalarangelo/mini.css#99]
Steps to reproduce:
1. Scroll down in Codepen's demo, until 'Hamburger's button is visible
2. Click on the 'Hamburger's button and press the 'Home' button. Focus moves to the beginning of the page 
3. Press the 'X' button to close the 'Hamburger's window and the current focus is returned in last known position before 'Home' being pressed. In this case focus returns (page is centered) on the 'Hamburger's button

Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit), Windows 7 SP1 64bit

**Comment by Chalarangelo** [comment]
This is the desired behavior for two main reasons:
1. Using `<label>` elements to toggle a menu like this is exactly how this would behave anywhere. Only alternative is using Javascript, which is not going to happen.
2. The `.drawer` and accompanying `.drawer-toggle` component are mainly meant to be part of a `<header>` element that has the `.sticky` class applied to it or is in a `positon: fixed` kind of situation. In terms of UX, this is the optimal way to use these components in order to not confuse users. In 99% of the use-cases I have seen, this has never been an issue.
